language: ruby
bundler_args: --without development
script: "bundle exec rake"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head
notifications:
  email: false
